// import { RowEntry, Schema, Messenger, ForeignKeyMap, PrimaryKey } from "@typedefs/SQL_TYPES";
// import SQL_ROW from "./SQL_ROW";

// class RowStash {
//     private primaryKey: string;
//     private rowMap: Map<string | number, RowEntry>;
  
//     constructor(primaryKey: string) {
//       this.primaryKey = primaryKey;
//       this.rowMap = new Map();
//     }
  
//     add(row: RowEntry) {
//       const key = row[this.primaryKey];
//       if (key === undefined) throw new Error("Row is missing primary key");
//       this.rowMap.set(key, row);
//     }
  
//     remove(id: string | number) {
//       return this.rowMap.delete(id);
//     }
  
//     get(id: string | number): RowEntry | undefined {
//       return this.rowMap.get(id);
//     }
  
//     getAll(): RowEntry[] {
//       return Array.from(this.rowMap.values());
//     }
  
//     toRaw(): RowEntry[] {
//       return this.getAll();
//     }
  
//     flushToSQLRows(
//       tableName: string,
//       schema: Schema,
//       callAddress: string,
//       messenger: Messenger,
//       foreignKeyMap: ForeignKeyMap,
//       isIdAutoGenerated: boolean
//     ): SQL_ROW[] {
//       return this.getAll().map(row => new SQL_ROW(
//         row,
//         tableName,
//         schema,
//         callAddress,
//         messenger,
//         this.primaryKey,
//         foreignKeyMap,
//         isIdAutoGenerated
//       ));
//     }
  
//     clear() {
//       this.rowMap.clear();
//     }
  
//     size() {
//       return this.rowMap.size;
//     }
//   }
  